import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import fs from 'node:fs';
const buf = fs.readFileSync('public/assets/characters/mage.glb');
const L = new GLTFLoader(); L.register((p) => ({ name: 'x', loadTexture: () => Promise.resolve(new THREE.Texture()) }));
const g = await L.parseAsync(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), '');
const leg = g.scene.getObjectByName('Mage_LegLeft');
const m = leg.isSkinnedMesh ? leg : leg.children.find(c=>c.isSkinnedMesh) ;
console.log(leg.type, m?.type, leg.children.map(c=>c.type+':'+c.name));
const geo = m.geometry, si = geo.attributes.skinIndex, sw = geo.attributes.skinWeight, p = geo.attributes.position;
console.log('pos type', p.array.constructor.name, p.normalized, 'si', si.array.constructor.name, 'sw', sw.array.constructor.name, sw.normalized, 'itemSize', si.itemSize);
for (const i of [0, 50, 100]) console.log(i, p.getX(i).toFixed(3), p.getY(i).toFixed(3), [0,1,2,3].map(k=>si.getComponent(i,k)+':'+sw.getComponent(i,k).toFixed(2)).join(' '), m.skeleton.bones[si.getComponent(i,0)].name);
console.log('matrixWorld leg', m.matrixWorld.elements.map(v=>v.toFixed(2)).join(','), 'parent', m.parent.name);
const { reproportionCharacter } = await import('../src/core/Proportions.ts');
const sk = m.skeleton;
const fi = sk.bones.findIndex(b=>b.name==='footl');
g.scene.updateMatrixWorld(true);
const v0 = new THREE.Vector3().fromBufferAttribute(p, 0);
console.log('old foot world y', sk.bones[fi].getWorldPosition(new THREE.Vector3()).y.toFixed(3), 'v0', v0.toArray().map(v=>v.toFixed(3)));
reproportionCharacter(g.scene);
const v1 = new THREE.Vector3().fromBufferAttribute(m.geometry.attributes.position, 0);
g.scene.updateMatrixWorld(true);
console.log('new foot world y', sk.bones[fi].getWorldPosition(new THREE.Vector3()).y.toFixed(3), 'v0 baked', v1.toArray().map(v=>v.toFixed(3)));
console.log('inv*world foot', sk.bones[fi].matrixWorld.clone().multiply(sk.boneInverses[fi]).elements.map(v=>v.toFixed(2)).join(','));
sk.update();
console.log('skinned v0', m.getVertexPosition(0, new THREE.Vector3()).toArray().map(v=>v.toFixed(3)));
